import Nav from "./components/Nav";
import "./globals.css";
import "./styles/framework.css";
import Head from "next/head";
import { baseTitle } from "@/utils/settings";
export const metadata = {
  title: baseTitle,
  description: "Generated by ❤️",
};

export default function RootLayout({ children }) {
  return (
    <html lang="da">
      <Head>
        <link rel="icon" href="/icon.svg" sizes="any" />
      </Head>
      <body>
        <Nav />
        {children}
      </body>
    </html>
  );
}
